import { MaintenanceItemProps } from "./MaintenanceItem";

export const maintenanceData:MaintenanceItemProps[] = [
  {
    name: "뉴발란스",
    logoUrl: "/images/maintenance/edited_nb.png",
    periodStart: "2019-03",
    periodEnd: "2023-06",
    description: "뉴발란스 코리아 공식 온라인 스토어 유지보수, 기획전 및 이벤트 페이지 제작 수행",
  },
  {
    name: "폴더",
    logoUrl: "/images/maintenance/edited_folder.png",
    periodStart: "2019-03",
    periodEnd: "2021-03",
    description: "폴더 공식 온라인 스토어 유지보수, 기획전 및 이벤트 페이지 제작 수행",
  },
  {
    name: "이랜드그룹",
    logoUrl: "/images/maintenance/edited_eland.png",
    periodStart: "2021-06",
    description: "이랜드그룹 공식 홈페이지 구축 후 유지보수 수행",
  },
  {
    name: "아워홈몰",
    logoUrl: "/images/maintenance/edited_ourhomemall.png",
    periodStart: "2025-11",
    description: "아워홈몰 메인 개편, 아워홈즈 체험단 등 주요 기능 개발 수행",
  },
  {
    name: "이랜드리테일",
    logoUrl: "/images/maintenance/edited_elandretail.png",
    periodStart: "2019-03",
    periodEnd: "2023-05",
    description: "이랜드리테일 공식 홈페이지 유지보수 수행",
  },
  {
    name: "이랜드CSR",
    logoUrl: "/images/maintenance/edited_elandcsr.png",
    periodStart: "2019-03",
    periodEnd: "2021-04",
    description: "이랜드CSR 공식 홈페이지 유지보수 수행",
  },
  {
    name: "이랜드이츠",
    logoUrl: "/images/maintenance/edited_elandeats.png",
    periodStart: "2019-03",
    periodEnd: "2021-11",
    description: "이랜드이츠 공식 홈페이지 유지보수 수행",
  },
  {
    name: "애슐리",
    logoUrl: "/images/maintenance/edited_ashley.png",
    periodStart: "2019-03",
    periodEnd: "2021-11",
    description: "애슐리 공식 홈페이지 유지보수 수행, 시즌 메뉴 및 이벤트 페이지 제작",
  },
  {
    name: "자연별곡",
    logoUrl: "/images/maintenance/edited_jabeol.png",
    periodStart: "2019-03",
    periodEnd: "2021-11",
    description: "자연별곡 공식 홈페이지 유지보수 수행, 시즌 메뉴 및 이벤트 페이지 제작",
  },
  {
    name: "더카페",
    logoUrl: "/images/maintenance/edited_thecaffee.png",
    periodStart: "2019-03",
    periodEnd: "2021-11",
    description: "더카페 공식 홈페이지 유지보수 수행",
  },
  {
    name: "로이드",
    logoUrl: "/images/maintenance/edited_lloyd.png",
    periodStart: "2021-05",
    description: "로이드 공식 온라인 스토어 유지보수, 기획전 및 이벤트 페이지 제작 수행",
  },
  {
    name: "켄싱턴 호텔/리조트",
    logoUrl: "/images/maintenance/edited_kensington.png",
    periodStart: "2019-03",
    periodEnd: "2020-03",
    description: "켄싱턴 호텔/리조트 공식 홈페이지 유지보수 수행",
  },
];
