import { ProjectCardProps } from "./ProjectCard";

export const projectsData:ProjectCardProps[] = [
  {
    title: "Portfolio Website",
    category: "Web Development",
    description: "A personal portfolio website to showcase my projects and skills.",
    imageUrl: "https://placehold.co/600x400/png?text=Portfolio+Website",
    projectLink: "/projects/portfolio-website",
    period: "Jan 2023 - Mar 2023",
    stack: ["React", "TypeScript", "CSS"],
  },
  {
    title: "E-commerce Platform",
    category: "Web Development",
    description: "An online platform for buying and selling products.",
    imageUrl: "https://placehold.co/600x400/png?text=E-commerce+Platform",
    projectLink: "/projects/ecommerce-platform",
    period: "Apr 2023 - Aug 2023",
    stack: ["Next.js", "Tailwind CSS", "Figma"],
  },
  {
    title: "Mobile Fitness App",
    category: "Mobile Development",
    description: "A mobile app to track workouts and fitness goals.",
    imageUrl: "https://placehold.co/600x400/png?text=Mobile+Fitness+App",
    projectLink: "/projects/mobile-fitness-app",
    period: "Sep 2023 - Dec 2023",
    stack: ["React", "Git", "Figma"],
  },
  {
    title: "Portfolio Website",
    category: "Web Development",
    description: "A personal portfolio website to showcase my projects and skills.",
    imageUrl: "https://placehold.co/600x400/png?text=Portfolio+Website",
    projectLink: "/projects/portfolio-website",
    period: "Jan 2023 - Mar 2023",
    stack: ["React", "TypeScript", "CSS"],
  },
  {
    title: "E-commerce Platform",
    category: "Web Development",
    description: "An online platform for buying and selling products.",
    imageUrl: "https://placehold.co/600x400/png?text=E-commerce+Platform",
    projectLink: "/projects/ecommerce-platform",
    period: "Apr 2023 - Aug 2023",
    stack: ["Next.js", "Tailwind CSS", "Figma"],
  },
  {
    title: "Mobile Fitness App",
    category: "Mobile Development",
    description: "A mobile app to track workouts and fitness goals.",
    imageUrl: "https://placehold.co/600x400/png?text=Mobile+Fitness+App",
    projectLink: "/projects/mobile-fitness-app",
    period: "Sep 2023 - Dec 2023",
    stack: ["React", "Git", "Figma"],
  },
  {
    title: "Portfolio Website",
    category: "Web Development",
    description: "A personal portfolio website to showcase my projects and skills.",
    imageUrl: "https://placehold.co/600x400/png?text=Portfolio+Website",
    projectLink: "/projects/portfolio-website",
    period: "Jan 2023 - Mar 2023",
    stack: ["React", "TypeScript", "CSS"],
  },
  {
    title: "E-commerce Platform",
    category: "Web Development",
    description: "An online platform for buying and selling products.",
    imageUrl: "https://placehold.co/600x400/png?text=E-commerce+Platform",
    projectLink: "/projects/ecommerce-platform",
    period: "Apr 2023 - Aug 2023",
    stack: ["Next.js", "Tailwind CSS", "Figma"],
  },
  {
    title: "Mobile Fitness App",
    category: "Mobile Development",
    description: "A mobile app to track workouts and fitness goals.",
    imageUrl: "https://placehold.co/600x400/png?text=Mobile+Fitness+App",
    projectLink: "/projects/mobile-fitness-app",
    period: "Sep 2023 - Dec 2023",
    stack: ["React", "Git", "Figma"],
  },
];
