import { ProjectCardProps } from "./ProjectCard";

export const projectsData:ProjectCardProps[] = [
  {
    title: "JTBC 뉴스 플랫폼 구축",
    projectLink: "https://news.jtbc.co.kr/",
    slug: "jtbc-news-renewal",
    category: "Media",
    client: "JTBC",
    description: "JTBC 뉴스 플랫폼 리빌딩을 위한 Next.js 및 MUI 기반의 반응형 UI 컴포넌트 개발, Storybook 구축",
    periodStart: "2024-01",
    periodEnd: "2024-12",
    stack: ["Next.js", "TypeScript", "MUI", "Recoil", "Emotion", "Storybook", "반응형", "Git", "Figma"],
  },
  {
    title: "KBS 방송 참여 플랫폼 구축",
    projectLink: "https://new-tvut.kbs.co.kr/",
    slug: "kbs-tvut",
    category: "Media",
    client: "KBS",
    description: "KBS 방송 참여 플랫폼 'Tvut' 구축을 위한 HTML 마크업 및 SASS 기반 스타일링, 사용자 인터랙션 개발",
    periodStart: "2023-01",
    periodEnd: "2023-07",
    stack: ["HTML", "Sass", "jQuery", "Git", "Photoshop"],
  },
  {
    title: "CJ 대한통운 임직원 커뮤니티 구축",
    category: "Community",
    slug: "cj-the-square",
    client: "CJ대한통운",
    description: "임직원 소통 활성화를 위한 모바일 웹 커뮤니티 'The Square' 구축. React 기반의 UI 컴포넌트 개발 및 모바일 웹 구현",
    periodStart: "2025-03",
    periodEnd: "2025-06",
    stack: ["React", "Tailwind CSS", "Styled-Components", "Git", "Figma"],
  },
  {
    title: "CJ 식자재 B2B eCommerce 구축",
    projectLink: "https://www.cjschoolfood.com/",
    category: "eCommerce",
    client: "CJ프레시웨이",
    description: "B2B 식자재 유통 플랫폼 'CJ 튼튼스쿨'의 반응형 웹사이트 구축 및 React 기반 UI 컴포넌트 개발",
    periodStart: "2025-06",
    periodEnd: "2025-08",
    stack: ["React", "Tailwind CSS", "Styled-Components", "반응형", "Git", "Figma"],
  },
  {
    title: "아워홈 품질관리시스템 고도화",
    category: "Service",
    client: "아워홈",
    description: "React 기반 어드민 웹사이트인 아워홈 품질관리시스템(QSIS) 고도화를 위한 기존 페이지 리뉴얼 수행",
    periodStart: "2025-02",
    periodEnd: "2025-04",
    stack: ["React", "Ant Design", "Styled-Components", "Git", "Figma"],
  },
  {
    title: "CJ 맥소노미 홈페이지 구축",
    projectLink: "https://maxonomy.net/",
    category: "Brand",
    client: "CJ 올리브네트웍스",
    description: "CJ 맥소노미의 브랜드 웹사이트 구축 중 UI/UX 이슈 트러블슈팅 지원",
    periodStart: "2024-01",
    periodEnd: "2024-12",
    stack: ["React", "Tailwind CSS", "Styled-Components", "반응형", "Git", "Figma"],
  },
  
  {
    title: "CJ 오클라우드 관리 플랫폼 구축",
    category: "Service",
    client: "CJ",
    description: "CJ 오클라우드 관리 콘솔의 웹 인터페이스 구축 및 jQuery를 활용한 동적 인터랙션 구현",
    periodStart: "2023-08",
    periodEnd: "2024-01",
    stack: ["HTML", "CSS", "jQuery", "Figma"],
  },
  {
    title: "투비소프트 홈페이지 구축",
    projectLink: "https://www.tobesoft.com/",
    category: "Brand",
    client: "투비소프트",
    description: "투비소프트 공식 홈페이지의 반응형 웹 UI 구현 및 jQuery 기반의 동적 기능 개발 지원",
    periodStart: "2022-10",
    periodEnd: "2022-12",
    stack: ["HTML", "CSS", "jQuery", "반응형", "Git", "Photoshop"],
  },
  {
    title: "아이봇로지스 홈페이지 구축", 
    projectLink: "https://aibotlogis.com/",
    category: "Brand",
    client: "아이봇로지스",
    description: "아이봇로지스 홈페이지 구축을 위한 HTML/CSS 기반 퍼블리싱 및 jQuery 인터랙션 개발",
    periodStart: "2022-09",
    periodEnd: "2022-10",
    stack: ["HTML", "CSS", "jQuery", "Git", "Photoshop"],
  },
  {
    title: "이랜드몰 리뉴얼",
    projectLink: "https://www.elandmall.co.kr/",
    category: "eCommerce",
    client: "이랜드",
    description: "이랜드몰 리뉴얼 프로젝트에서 기존 페이지의 컴포넌트화 및 HTML/CSS 구현, 프리랜서 인력 관리 및 일정 조율 담당",
    periodStart: "2022-01",
    periodEnd: "2022-06",
    stack: ["HTML", "CSS", "jQuery", "Git"],
  },
  {
    title: "이랜드그룹 홈페이지 구축",
    projectLink: "https://www.eland.co.kr/",
    category: "Brand",
    client: "이랜드",
    description: "HTML/CSS 기반 반응형 퍼블리싱 및 jQuery 인터랙션 개발을 통한 이랜드그룹 공식 홈페이지 구축",
    periodStart: "2022-06",
    periodEnd: "2022-09",
    stack: ["HTML", "CSS", "jQuery", "반응형", "Photoshop"],
  },
  {
    title: "쥬얼리/잡화 플랫폼 구축",
    category: "eCommerce",
    client: "이랜드패션",
    description: "이랜드패션의 쥬얼리/잡화 전문 eCommerce 플랫폼 구축을 위한 HTML/CSS 반응형 웹 퍼블리싱 및 jQuery 인터랙션 개발",
    periodStart: "2020-10",
    periodEnd: "2021-01",
    stack: ["HTML", "CSS", "jQuery", "반응형", "Photoshop"],
  },
  {
    title: "반려동물 통합 플랫폼 구축",
    category: "eCommerce",
    client: "RADCNS",
    description: "반려동물 용품 및 커뮤니케이션 플랫폼 구축을 위한 HTML/CSS 반응형 웹 퍼블리싱 및 jQuery 인터랙션 개발",
    periodStart: "2020-09",
    periodEnd: "2020-10",
    stack: ["HTML", "CSS", "jQuery", "반응형", "Photoshop"],
  },
  {
    title: "아동 패션 플랫폼 구축",
    projectLink: "https://kidikidi.elandmall.co.kr/",
    category: "eCommerce",
    client: "이랜드리테일",
    description: "아동 패션 플랫폼 구축을 위한 HTML/CSS 반응형 웹 퍼블리싱 및 jQuery 인터랙션 개발",
    periodStart: "2020-02",
    periodEnd: "2020-05",
    stack: ["HTML", "CSS", "jQuery", "반응형", "Photoshop"],
  },
  {
    title: "글로벌 eSports 대회 공식 웹사이트 구축",
    category: "Brand",
    client: "Smilegate",
    description: "WCG 2019 공식 웹사이트의 다국어 반응형 UI 개발 및 중국 시안 현지 행사 운영 기술 지원",
    imageUrlAry: ["/images/projects/wcg2019_01.jpg", "/images/projects/wcg2019_02.jpg", "/images/projects/wcg2019_03.jpg"],
    periodStart: "2019-07",
    periodEnd: "2020-02",
    stack: ["HTML", "CSS", "jQuery", "반응형", "다국어", "Photoshop"],
  },
];
